name: Deploy Kong API Gateway

on:
  push:
    branches: [ main ]
    paths:
      - kong/**
      - docker-compose.yml

env:
  AWS_REGION: us-east-2
  EC2_INSTANCE_ID: i-080d526874aee8c0e
  APP_DIR: /opt/kong-api-gateway

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Assume AWS role (same as backend)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::589335871756:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      # # Validate kong.yml before touching EC2
      # - name: Validate Kong config
      #   run: |
      #     docker run --rm \
      #       -e KONG_DATABASE=off \
      #       -e KONG_DECLARATIVE_CONFIG=/kong/kong.yml \
      #       -v $PWD/kong/kong.yml:/kong/kong.yml \
      #       kong:3.6 kong config parse /kong/kong.yml

      # Deploy via SSM
      - name: Deploy Kong via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${EC2_INSTANCE_ID}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Kong API Gateway" \
            --parameters commands='[
              "set -e",
              "cd /opt/kong-api-gateway",
              "git pull origin main",
              "docker compose down",
              "docker compose up -d"
            ]'
